bigday/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from accounts import views as accounts_views


urlpatterns = [
    url(r'^', include('wedding.urls')),
    url(r'^', include('guests.urls')),
    url(r'^admin/', admin.site.urls),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', accounts_views.signup, name='signup'),
]

guests/urls.py
from django.conf.urls import url

from guests.views import GuestListView, test_email, save_the_date_preview, save_the_date_random, export_guests, \
    invitation, invitation_email_preview, invitation_email_test, rsvp_confirm, dashboard

urlpatterns = [
    url(r'^guests/$', GuestListView.as_view(), name='guest-list'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^guests/export$', export_guests, name='export-guest-list'),
    url(r'^invite/(?P<invite_id>[\w-]+)/$', invitation, name='invitation'),
    url(r'^invite-email/(?P<invite_id>[\w-]+)/$', invitation_email_preview, name='invitation-email'),
    url(r'^invite-email-test/(?P<invite_id>[\w-]+)/$', invitation_email_test, name='invitation-email-test'),
    url(r'^save-the-date/$', save_the_date_random, name='save-the-date-random'),
    url(r'^save-the-date/(?P<template_id>[\w-]+)/$', save_the_date_preview, name='save-the-date'),
    url(r'^email-test/(?P<template_id>[\w-]+)/$', test_email, name='test-email'),
    url(r'^rsvp/confirm/(?P<invite_id>[\w-]+)/$', rsvp_confirm, name='rsvp-confirm'),
]

guests/models.py
from __future__ import unicode_literals
import datetime
import uuid

from django.db import models
from django.dispatch import receiver

# these will determine the default formality of correspondence
ALLOWED_TYPES = [
    ('rodzina_adama', 'rodzina_adama'),
    ('rodzina_kasi', 'rodzina_kasi'),
    ('znajomi_adama', 'znajomi_adama'),
    ('znajomi_kasi', 'znajomi_kasi'),
    ('randomy', 'randomy'),
    ('gospodarze', 'gospodarze'),
]


def _random_uuid():
    return uuid.uuid4().hex[:5].upper()


class Party(models.Model):
    """
    A party consists of one or more guests.
    """
    name = models.TextField()
    type = models.CharField(max_length=15, choices=ALLOWED_TYPES)
    category = models.CharField(max_length=20, null=True, blank=True)
    save_the_date_sent = models.DateTimeField(null=True, blank=True, default=None)
    save_the_date_opened = models.DateTimeField(null=True, blank=True, default=None)
    invitation_id = models.CharField(max_length=5, db_index=True, default=_random_uuid, unique=True)
    invitation_sent = models.DateTimeField(null=True, blank=True, default=None)
    invitation_opened = models.DateTimeField(null=True, blank=True, default=None)
    is_invited = models.BooleanField(default=False)
    rehearsal_dinner = models.BooleanField(default=False)
    is_attending_ceremony = models.NullBooleanField(default=None)
    email = models.TextField(null=True, blank=True, max_length=35)
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'Party: {}'.format(self.name)

    @classmethod
    def in_default_order(cls):
        return cls.objects.order_by('category', '-is_invited', 'name')

    @property
    def ordered_guests(self):
        return self.guest_set.order_by('is_child', 'pk')

    @property
    def any_guests_attending(self):
        return any(self.guest_set.values_list('is_attending_ceremony', flat=True))

    @property
    def guest_emails(self):
        return list(filter(None, self.guest_set.values_list('email', flat=True)))


MEALS = [
    ('meat', 'standardowego'),
    ('vegetarian', 'wegetariańskiego'),
]


class Guest(models.Model):
    """
    A single guest
    """
    party = models.ForeignKey('Party', on_delete=models.CASCADE)
    unknown_name = models.BooleanField(default=False)
    first_name = models.TextField(null=True, blank=True, max_length=20)
    last_name = models.TextField(null=True, blank=True, max_length=20)
    email = models.TextField(null=True, blank=True, max_length=30)
    is_attending_ceremony = models.NullBooleanField(default=None)
    meal = models.CharField(max_length=20, choices=MEALS, null=True, blank=True)
    is_child = models.BooleanField(default=False)
    is_accommodation_needed = models.NullBooleanField(default=None)
    is_attending_aftermath = models.NullBooleanField(default=None)

    @property
    def name(self):
        return u'{} {}'.format(self.first_name, self.last_name)

    @property
    def unique_id(self):
        # convert to string so it can be used in the "add" templatetag
        return str(self.pk)

    def __str__(self):
        return 'Guest: {} {}'.format(self.first_name, self.last_name)

guests/views.py
import base64
from collections import namedtuple
import random
import sys
from datetime import datetime
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Count, Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from guests import csv_import
from guests.invitation import get_invitation_context, INVITATION_TEMPLATE, guess_party_by_invite_id_or_404, \
    send_invitation_email
from guests.models import Guest, MEALS, Party
from guests.save_the_date import get_save_the_date_context, send_save_the_date_email, SAVE_THE_DATE_TEMPLATE, \
    SAVE_THE_DATE_CONTEXT_MAP
from pprint import pprint
from guests.email_sender import send_email


class GuestListView(ListView):
    model = Guest


@login_required
def export_guests(request):
    export = csv_import.export_guests()
    response = HttpResponse(export.getvalue(), content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=all-guests.csv'
    return response


@login_required
def dashboard(request):
    parties_with_pending_invites = Party.objects.filter(
        is_invited=True, is_attending=None
    ).order_by('category', 'name')
    parties_with_unopen_invites = parties_with_pending_invites.filter(invitation_opened=None)
    parties_with_open_unresponded_invites = parties_with_pending_invites.exclude(invitation_opened=None)
    attending_guests = Guest.objects.filter(is_attending=True)
    guests_without_meals = attending_guests.filter(
        is_child=False
    ).filter(
        Q(meal__isnull=True) | Q(meal='')
    ).order_by(
        'party__category', 'first_name'
    )
    meal_breakdown = attending_guests.exclude(meal=None).values('meal').annotate(count=Count('*'))
    category_breakdown = attending_guests.values('party__category').annotate(count=Count('*'))
    return render(request, 'guests/dashboard.html', context={
        'guests': Guest.objects.filter(is_attending=True).count(),
        'possible_guests': Guest.objects.filter(party__is_invited=True).exclude(is_attending=False).count(),
        'not_coming_guests': Guest.objects.filter(is_attending=False).count(),
        'pending_invites': parties_with_pending_invites.count(),
        'pending_guests': Guest.objects.filter(party__is_invited=True, is_attending=None).count(),
        'guests_without_meals': guests_without_meals,
        'parties_with_unopen_invites': parties_with_unopen_invites,
        'parties_with_open_unresponded_invites': parties_with_open_unresponded_invites,
        'unopened_invite_count': parties_with_unopen_invites.count(),
        'total_invites': Party.objects.filter(is_invited=True).count(),
        'meal_breakdown': meal_breakdown,
        'category_breakdown': category_breakdown,
    })


def invitation(request, invite_id):
    guests = []
    party = guess_party_by_invite_id_or_404(invite_id)
    if party.invitation_opened is None:
        # update if this is the first time the invitation was opened
        party.invitation_opened = datetime.utcnow()
        party.save()
    if request.method == 'POST':
        params = request.POST
        for response in _parse_invite_params(params):
            guest = Guest.objects.get(pk=response.guest_pk)
            assert guest.party == party
            guest.is_attending_ceremony = response.is_attending_ceremony
            guest.meal = response.meal
            guest.is_accommodation_needed = response.is_accommodation_needed
            guest.is_attending_aftermath = response.is_attending_aftermath
            if 'first_name' in params and guest.unknown_name:
                guest.first_name = params['first_name']
            if 'last_name' in params and guest.unknown_name:
                guest.last_name = params['last_name']
            guest.save()
            guests.append(guest)
        if request.POST.get('comments'):
            comments = request.POST.get('comments')
            party.comments = comments if not party.comments else '{}; {}'.format(party.comments, comments)
        if request.POST.get('email'):
            email = request.POST.get('email')
            party.email = email if not party.email else '{}; {}'.format(party.email, email)
        party.is_attending_ceremony = party.any_guests_attending
        party.save()
        pprint(vars(party))
        print(type(party))
        send_email(party, guests)
        return HttpResponseRedirect(reverse('rsvp-confirm', args=[invite_id]))
    return render(request, template_name='guests/invitation.html', context={
        'party': party,
        'meals': MEALS,
    })


InviteResponse = namedtuple('InviteResponse', ['guest_pk', 'is_attending_ceremony', 'meal', 'is_accommodation_needed',
                                               'is_attending_aftermath'])


def _parse_invite_params(params):
    responses = {}
    for param, value in params.items():
        if param.startswith('attending'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['attending'] = True if value == 'yes' else False
            responses[pk] = response
        elif param.startswith('meal'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['meal'] = value
            responses[pk] = response
        elif param.startswith('accommodation'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['accommodation'] = True if value == 'yes' else False
            responses[pk] = response
        elif param.startswith('aftermath'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['aftermath'] = True if value == 'yes' else False
            responses[pk] = response

    for pk, response in responses.items():
        yield InviteResponse(pk, response['attending'], response.get('meal', None), response.get('accommodation', None),
                             response.get('aftermath', None))


def rsvp_confirm(request, invite_id=None):
    party = guess_party_by_invite_id_or_404(invite_id)
    return render(request, template_name='guests/rsvp_confirmation.html', context={
        'party': party,
        'support_email': settings.DEFAULT_WEDDING_REPLY_EMAIL,
    })


@login_required
def invitation_email_preview(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    context = get_invitation_context(party)
    return render(request, INVITATION_TEMPLATE, context=context)


@login_required
def invitation_email_test(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    send_invitation_email(party, recipients=[settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')


def save_the_date_random(request):
    template_id = random.choice(SAVE_THE_DATE_CONTEXT_MAP.keys())
    return save_the_date_preview(request, template_id)


def save_the_date_preview(request, template_id):
    context = get_save_the_date_context(template_id)
    context['email_mode'] = False
    return render(request, SAVE_THE_DATE_TEMPLATE, context=context)


@login_required
def test_email(request, template_id):
    context = get_save_the_date_context(template_id)
    send_save_the_date_email(context, [settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')


def _base64_encode(filepath):
    with open(filepath, "rb") as image_file:
        return base64.b64encode(image_file.read())

guests/templates/guests/dashboard.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container" id="main">
        <h1>Dashboard</h1>
        <table class="table table-striped">
            <tr>
                <td>Guests Attending / Possible</td>
                <td>{{ guests }} / {{ possible_guests }}</td>
            </tr>
            <tr>
                <td>Pending Invitations</td>
                <td>{{ pending_invites }} ({{ pending_guests }} guests)</td>
            </tr>
            <tr>
                <td>Unopened Invitations</td>
                <td>{{ unopened_invite_count }}<span class="text-muted"> / {{ total_invites }}</span></td>
            </tr>
            <tr>
                <td>Not Coming</td>
                <td>{{ not_coming_guests }}</td>
            </tr>
            </tbody>
        </table>
        <div class="row">
            <div class="col-lg-6">
                <h1>Guests by category</h1>
                <table class="table">
                    <thead>
                        <tr>
                            {% for category in category_breakdown %}
                            <th>{{ category.party__category }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for category in category_breakdown %}
                            <td>{{ category.count }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-6">
                <h1>Meal choices</h1>
                <table class="table">
                    <thead>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <th>{{ meal.meal }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <td>{{ meal.count }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h1>Unopened Invitations</h1>
                {% with party_list=parties_with_unopen_invites %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
            <div class="col-lg-6">
                <h1>Open Unresponded Invitations</h1>
                {% with parties_with_open_unresponded_invites as party_list %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
        </div>
        <div class="col-lg-6">
                <h1>Attending Guests Without Meals</h1>
                {% with guest_list=guests_without_meals %}
                    {% include "guests/partials/guest_list.html" %}
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}

guests/templates/guests/invitation.html
{% extends 'base.html' %}
{% load static %}
{% block page_head %}
    <link href="{% static 'bigday/css/invitation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
    <div class="container" id="invitation-body">
        <section class="video-container">
                <img src="{% static 'bigday/images/invite-image.jpg' %}" class="img-responsive" alt="">
        </section>
        <section class="col-md-6 text-center">
            <div id="invitation-details">
            <h2>Kasia i Adam</h2>
            <p class="lead">
                Hotel Bursztynowy Sen<br>
                Sala Syrenka<br>
                Grunwaldzka 13, 82-103 Stegna<br>
            </p>
                <hr size="2" width="90%" color="black">
                <h2>Ślub</h2> <br>
                <p class="lead">
                    18 września 2021, 17:00 - 17:15
                </p><br>
                <hr size="2" width="90%" color="black">
                <h2>Wesele</h2> <br>
                <p class="lead">
                    18 września 2021, 17:15 - 4:20
                </p><br>
                <hr size="2" width="90%" color="black">
                <h2>Poprawiny</h2> <br>
                <p class="lead">
                    19 września 2021, 13:00 - 16:00</h3>
            </p>
            </div>
        </section>
        {% if not party.is_attending_ceremony %}
        <section class="col-md-6">
        <form data-toggle="validator" id="invitation-details" class="form-horizontal" method="post">
            <h2 id="rsvp-header" class="text-center">RSVP</h2>
            <div class="clearfix"></div>
            {% csrf_token %}
            {% for guest in party.ordered_guests.all %}
            {% if guest.unknown_name %}
                <div class="form-group col-sm-6 grayed">
                    {% with 'first_name-'|add:guest.unique_id as fist_name_label %}
                    <input type="text" name="first_name" id="first_name" class="form-control"  placeholder="Imię osoby towarzyszącej" required>
                    {% endwith %}
                </div>
                <div class="form-group col-sm-6 grayed">
                    {% with 'last_name-'|add:guest.unique_id as last_name_label %}
                    <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Nazwisko osoby towarzyszącej" required>
                    {% endwith %}
                </div>
            {% endif %}
            <div class="form-group row grayed text-center" data-is-child="{{ guest.is_child }}">
                {% with 'attending-'|add:guest.unique_id as attending_label %}
                    <div class="form-check">
                {% if not guest.unknown_name %}
                    <div class="radio-inline" style="text-align: center;">
                        <label style="text-align: center;">{{ guest.name }}</label>
                    </div><br>
                {% endif %}
                {% if guest.unknown_name %}
                    <div class="radio-inline" style="text-align: center;">
                        <label style="text-align: center;">Osoba towarzysząca</label>
                    </div><br>
                {% endif %}
                <div class="radio-inline">
                    <label>
                        <input class="attending-radio" type="radio" name="{{ attending_label }}" id="yes-{{ attending_label }}" value="yes" {% if guest.is_attending_ceremony %}checked="checked"{% endif %} required>przybędzie</label>
                </div><div class="radio-inline"><label>
                                 <input class="attending-radio" type="radio" name="{{ attending_label }}" id="no-{{ attending_label }}" value="no" {% if guest.is_attending_ceremony == False %}checked="checked"{% endif %} required> nie przybędzie</label>
                    </div>
                </div>
                {% endwith %}
            </div><br>
            {% if not guest.is_child %}
            <div class="form-group grayed text-center">
                {% with 'meal-'|add:guest.unique_id as meal_label %}
                <div class="radio-inline" style="text-align: center;">
                    <label style="text-align: center;">skorzysta z menu</label>
                </div><br>
                {% for meal_id, meal_name in meals %}
                <label class="radio-inline">
                    <input type="radio" name="{{ meal_label }}" id="{{ meal_id }}-{{ meal_label }}" value="{{ meal_id }}" {% if guest.meal == meal_id %}checked="checked"{% endif %} required> {{ meal_name }}
                </label>
                {% endfor %}
                {% endwith %}
            </div><br>
            <div class="form-group grayed text-center">
                {% with 'accommodation-'|add:guest.unique_id as accommodation_label %}
                <div class="radio-inline" style="text-align: center;">
                    <label style="text-align: center;">miejsce noclegowe</label>
                </div><br>
                <label class="radio-inline">
                    <input class="accommodation-radio" type="radio" name="{{ accommodation_label }}" id="yes-{{ accommodation_label }}" value="yes" {% if guest.is_accommodation_needed %}checked="checked"{% endif %} required> potrzebuje
                </label>
                <label class="radio-inline">
                    <input class="accommodation-radio" type="radio" name="{{ accommodation_label }}" id="no-{{ accommodation_label }}" value="no" {% if guest.is_accommodation_needed == False %}checked="checked"{% endif %} required>nie potrzebuje
                </label>
                {% endwith %}
            </div><br>
            <div class="form-group grayed text-center">
                {% with 'aftermath-'|add:guest.unique_id as aftermath_label %}
                <div class="radio-inline" style="text-align: center;">
                    <label style="text-align: center;">na poprawiny</label>
                </div><br>
                <label class="radio-inline">
                    <input class="btn btn-primary" type="radio" name="{{ aftermath_label }}" value="yes" id="yes-{{ aftermath_label }}" {% if guest.is_attending_aftermath %}checked="checked"{% endif %} required>przybędzie
                </label>
                <label class="radio-inline">
                    <input class="aftermath-radio" type="radio" name="{{ aftermath_label }}" value="no" id="no-{{ aftermath_label }}" {% if guest.is_attending_aftermath == False %}checked="checked"{% endif %} required>nie przybędzie
                </label>
                {% endwith %}
            </div>
            {% endif %}
                <hr size="2" width="90%" color="black">
            {% endfor %}
            <div class="form-group col-sm-12">
                <input type="text" name="email" class="form-control" placeholder="e-mail" >
            </div>
            <div class="form-group col-sm-12">
                <input type="text" name="comments" class="form-control" placeholder="Pytania / komentarze / życzenia / zażalenia / ***** ***" >
            </div>
            <div class="form-group">
                <div class="text-center">
                    <input type="submit" class="btn btn-primary" value="Wyślij odpowiedź" />
                </div>
            </div>
        </form>
        </section>
    {% endif %}
    {% if party.is_attending_ceremony %}
    <section class="col-md-6">
        <form data-toggle="validator" id="invitation-details" class="form-horizontal" method="post">
            <h2 id="rsvp-header" class="text-center">Dziękujęmy za potwierdzenie zaproszenia<br>Do zobaczenia!</h2>
        </form>
    </section>
    {% endif %}
    </div>
{% endblock %}
{% block page_js %}
    <script src="{% static 'validator.js' %}"></script>
    <script>
    $(function () {
        $("input.attending-radio").change(function (e) {
            var notAttendingList = document.querySelectorAll('[id^="no-attending"]')
            for(var i = 0; i < notAttendingList.length; i++)
                {
                    var clientId = notAttendingList[i].id.match(/\d+/)[0];
                    var elementIds = ["meat-meal-", "vegetarian-meal-", "yes-accommodation-", "no-accommodation-", "yes-aftermath-", "no-aftermath-"];
                    if (notAttendingList[i].checked) {
                        elementIds.forEach(function (element) {
                            var elementToDisable = "#"+element+clientId
                            document.querySelector(elementToDisable).disabled = true;
                            document.querySelector(elementToDisable).required = false;
                            if (i !== 0 &&  document.querySelector("#first_name") !== null) {
                                document.querySelector("#first_name").disabled = true;
                                document.querySelector("#first_name").required = false;
                                document.querySelector("#last_name").disabled = true;
                                document.querySelector("#last_name").required = false;
                            }
                            if (i === 0) {
                                var sasin = "#yes-attending-"+(parseInt(clientId, 10)+1)
                                var jebacPis = "#no-attending-"+(parseInt(clientId, 10)+1)
                                document.querySelector(jebacPis).click()
                                document.querySelector(jebacPis).disabled = true;
                                document.querySelector(jebacPis).required = false;
                                document.querySelector(sasin).disabled = true;
                                document.querySelector(sasin).required = false;
                            }
                        });
                    }
                    else {
                        elementIds.forEach(function (element) {
                            var elementToDisable = "#"+element+clientId
                            document.querySelector(elementToDisable).disabled = false;
                            document.querySelector(elementToDisable).required = true;
                            if (i !== 0 && document.querySelector("#first_name") !== null) {
                                document.querySelector("#first_name").disabled = false;
                                document.querySelector("#first_name").required = true;
                                document.querySelector("#last_name").disabled = false;
                                document.querySelector("#last_name").required = true;
                            }
                            if (i === 0) {
                                var sasin = "#yes-attending-"+(parseInt(clientId, 10)+1)
                                var jebacPis = "#no-attending-"+(parseInt(clientId, 10)+1)
                                document.querySelector(jebacPis).disabled = false;
                                document.querySelector(jebacPis).required = true;
                                document.querySelector(sasin).disabled = false;
                                document.querySelector(sasin).required = true;
                            }
                        });
                    }
                }
            $(document.forms[0]).validator('destroy');
            $(document.forms[0]).validator();
        });
    });
    </script>
{% endblock %}

guests/templates/guests/rsvp_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block page_head %}
    <link href="{% static 'bigday/css/rsvp-confirmation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
    <div class="layer"></div>
    <div class="container" id="main">
        <h2>Cześć {{ party.name }}! Dziękuję za odpowiedź!</h2>
        {% if party.any_guests_attending %}
            <p>
                Nie możemy się doczekać, aby świętować z Tobą na naszym weselu! =)
            </p>
            <p>
                Jeśli masz inne pytania, napisz do nas na adres <a href="mailto:{{ support_email }}">{{ support_email }}</a>.
            </p>
        {% else %}
            <p>
                Przykro nam, że nie będziesz mógł dołączyć do nas w Stegnie :c.
            </p>
            <p>
                Z niecierpliwością czekamy na spotkanie z Tobą innym razem!
            </p>
        {% endif %}
        <p>
            - Kasia i Adam
        </p>
        <a href="../../../../" class="btn btn-info btn-xl page-scroll">Powrót na stronę główną</a>
    </div>
{% endblock %}